//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using RolePermission.Model.Relationship;

namespace RolePermission.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMFUNCTB
    {
        public SMFUNCTB()
        {
            this.SMMENUROLEFUNCTB = new List<SMMENUROLEFUNCTB>();
            this.SMMENUTB = new List<MenuFunc>();
        }
    
        [Key]
        public int FUNC_ID { get; set; }
        public string FUNC_CODE { get; set; }
        public string FUNC_NAME { get; set; }
        public string EVENT_NAME { get; set; }
        public string STATUS { get; set; }
        public string PARENTFUNC_CODE { get; set; }
        public string CLASS_NAME { get; set; }
        public Nullable<int> ORDERCODE { get; set; }
        public string SM_SYSTEM { get; set; }
        public string ICONIC { get; set; }
        [Display(Name = "菜单")]
        [NotMapped]
        public string SysMenuId { get; set; }
    
        public virtual IList<SMMENUROLEFUNCTB> SMMENUROLEFUNCTB { get; set; }
        public virtual IList<MenuFunc> SMMENUTB { get; set; }
    }
}
